Add support to syzcmd for "syz basedir ..." and "syz cd ...".

diff --git a/bin/syzcmd b/bin/syzcmd
--- a/bin/syzcmd
+++ b/bin/syzcmd
@@ -21,5 +21,31 @@
 . shwrapnel || { echo "shwrapnel: Error: cannot source shwrapnel" 1>&2 ; exit 1; }
 
 shwrapnel set_real_cmd modulecmd
-shwrapnel launch
+
+if [ "$2" = "basedir" ]; then
+	shwrapnel run "$1" show "$3" 2>&1 | sed -ne 's,^setenv\s\+[A-Za-z0-9_]\+_BASE\s\+,echo ,p'
+
+elif [ "$2" = "cd" ]; then
+	if [ $# -eq 2 ]; then
+		# The user has done "syz cd", probably absent-mindedly trying to get back to their home dir.
+		echo "cd"
+		exit 0
+	fi
+	if [ "$3" = - ]; then
+		# Another likely brainfart.
+		echo "cd -"
+		exit 0
+	fi
+
+	basedir="$(syz basedir "$3")"
+	if [ "$basedir" = "" ]; then
+		echo "syzcmd: Error: \"$3\" not found" 1>&2
+		exit 1
+	fi
+	echo "cd $basedir"
+
+else
+	shwrapnel launch
+
+fi
 
