syzln: Add basic error checking to the ln commands.

diff --git a/bin/syzln b/bin/syzln
--- a/bin/syzln
+++ b/bin/syzln
@@ -42,7 +42,10 @@ function process_tree {
 					echo -ne "#%Module1.0\nset ModulesVersion "\""$target"\""\n" > .sf/"$pkgname"/.version
 					echo "Set $pkgname default to $target"
 				else
-					ln -svf ../../"$j"/syzfile .sf/"$pkgname/$version"
+					if ! ln -svf ../../"$j"/syzfile .sf/"$pkgname/$version"; then
+						echo "Error, aborting"
+						return 1
+					fi
 				fi
 			done
 			echo "" 1>&2
